---
title: "Project 1-Group A"
author: "Zhen Jiang"
date: "Sep. 28, 2018"
output:
  html_document:
    toc: yes
    toc_depth: 1
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# What is JSON data, where does it get used, and why is it a good way to store data?
## 
JSON, short for Javascript Object Notation, is a data format represented as a string that can be used to store ordered lists or name-value pairs. It is intuitive for humans and understood by many computer languages, despite its origins in Javascript. It is used most regularly in data interchange, or the transfer of structured information between servers and web applications. Vectors and arrays in JSON format are represented with square brackets and comma delimiters, while objects or name-value pairs use curly brackets and comma delimiters. Compared to the comma separated values format, JSON is better at showing hierarchical data and is easy to use with better data reading programs than Microsoft Excel. Compared to XML, JSON is smaller, faster for computers to read, and more intuitive for humans to look at raw. Since many web-based applications are coded using Javascript, at least one end of the channel will natively understand JSON, making it a convenient format for data interchange.

# Possible packages/functions (pros/cons) that are available for reading JSON data into R. Choose one and explain why you’ve chosen it. 
## Possible packages for reading JSON data into R
1, The rjson package.
   We can use this package for reading in JSON files in R.

2, The fromJSON function in the rjson package.
   Pros: We can use this function to easily read in JSON files into R as a list and change it into any data type we want later.
   Cons: when using this function, we can only readin JSON files as list in R, and will have to convert it into atomic vector, data frame, or matrix using as... functions.
   
3, The jsonlite package.
   Pros: Implements a bidirectional mapping between JSON data and the most important R data types. Thereby we can convert between R objects and JSON without loss of type or information, and without the need for any manual data munging.
   Cons:

4, The fromJSON function in the jsonlite package.
   Pros: converts JSON arrays automatically into different types of R objects.
   This function has 3 arguments which control the converting process: simplifyVector, simplifyDataFrame and simplifyMatrix for converting JSON data into atomic vector, data frame, and matrix in R separately.
   cons: need to provide more arguments when using the function to determine what kind of data type we want in R.
 

# Give an example where you read in a JSON file and summarize that data set.
##
